### ISSUE TITLE
Fuel Log - for EU countries

### ISSUE THREAD

**Issue by michalagata** [jantman/biweeklybudget#159]
Please enable possibility to configure units for countries outside US, allowing to operate on:

- kilometers
- liters
- other currency than dollars

**Comment by jantman** [comment]
@michalagata Hi! You're the first person I know of to use this project, or at least the first person to open an issue on it. So I guess cool!

I can't promise how soon I'll have this done, but it's nice to know that someone else is interested in this project, so I'll get to work on it. Hopefully I can get a new release out with this within the week, if not sooner.

**Comment by jantman** [comment]
@michalagata Ok, I believe I have this implemented in the [issues/159](https://github.com/jantman/biweeklybudget/tree/issues/159) branch. Is there any chance that you'd be willing and able to test running from the branch to see if the fix looks correct to you?

**Comment by jantman** [comment]
This was released just now in [0.7.0](https://github.com/jantman/biweeklybudget/releases/tag/0.7.0). The release is live on [PyPI](https://pypi.python.org/pypi/biweeklybudget/0.7.0) and the [docker hub](https://hub.docker.com/r/jantman/biweeklybudget/).

**Comment by michalagata** [comment]
Sorry, gmail identified notification as spam. Works perfectly, as the whole project. Thank You! :)

**Comment by jantman** [comment]
Great to hear! Thanks so much for getting back to me!
